import { put } from '@vercel/blob';
import path from 'node:path';
import crypto from 'node:crypto'; // Added for hash calculation
import { embed, generateText } from 'ai'; // Added for embedding and text gen
import { openai } from '@ai-sdk/openai'; // Added for models
import { pool } from '@/lib/db'; // Added for database access
import { callGetImgApi } from './getimg-api';

// --- Model Definitions ---
const EMBEDDING_MODEL = openai.embedding('text-embedding-3-small');
const SHORT_NAME_MODEL = openai('gpt-4o-mini'); // Using gpt-4o-mini for short name
const SHORT_NAME_PROMPT_TEMPLATE =
  'Generate a very short (3-5 words) title or label for an image based on the following description: "{description}"';

// --- Helper Function Refactored ---

/**
 * Downloads an image from a URL, returns its buffer and determined filename.
 * @param getimgUrl The URL of the image generated by getimg.ai.
 * @returns Object containing the image buffer, filename, and content type if successful, otherwise null.
 */
async function downloadImageFromUrl(getimgUrl: string): Promise<{
  buffer: Buffer;
  filename: string;
  contentType: string | null;
} | null> {
  try {
    console.log(`[Image Util] Downloading image from: ${getimgUrl}`);
    const fetchResponse = await fetch(getimgUrl);
    if (!fetchResponse.ok) {
      throw new Error(
        `Failed to download image (${fetchResponse.status}): ${fetchResponse.statusText}`,
      );
    }
    const imageArrayBuffer = await fetchResponse.arrayBuffer();
    const imageBuffer = Buffer.from(imageArrayBuffer); // Convert ArrayBuffer to Buffer
    const contentType = fetchResponse.headers.get('content-type');
    console.log(`[Image Util] Downloaded ${imageBuffer.byteLength} bytes.`);

    // Determine Filename from getimg.ai URL
    const parsedGetimgUrl = new URL(getimgUrl);
    const getimgFilename = path.basename(parsedGetimgUrl.pathname);
    if (!getimgFilename || getimgFilename === '/' || getimgFilename === '.') {
      throw new Error(
        `Could not extract valid filename from URL: ${getimgUrl}`,
      );
    }
    return { buffer: imageBuffer, filename: getimgFilename, contentType };
  } catch (error) {
    console.error(`[Image Util] Error downloading ${getimgUrl}:`, error);
    return null;
  }
}

/**
 * Calculates the SHA256 hash of a buffer.
 * @param buffer The input buffer.
 * @returns The hex-encoded SHA256 hash.
 */
function calculateHash(buffer: Buffer): string {
  return crypto.createHash('sha256').update(buffer).digest('hex');
}

/**
 * Generates a short name for an image based on its description.
 * @param description The image description.
 * @returns The generated short name, or null on failure.
 */
async function generateShortName(description: string): Promise<string | null> {
  if (!description) return null;
  try {
    const prompt = SHORT_NAME_PROMPT_TEMPLATE.replace(
      '{description}',
      description,
    );
    const { text } = await generateText({
      model: SHORT_NAME_MODEL,
      prompt: prompt,
      maxTokens: 20, // Limit tokens for a short name
    });
    return text.trim().replace(/["']/g, ''); // Remove quotes if AI adds them
  } catch (error) {
    console.error('[Image Util] Failed to generate short name:', error);
    return null;
  }
}

/**
 * Generates an embedding for a given text description.
 * @param description The text description.
 * @returns The embedding vector, or null on failure.
 */
async function generateImageEmbedding(
  description: string,
): Promise<number[] | null> {
  if (!description) return null;
  try {
    const { embedding } = await embed({
      model: EMBEDDING_MODEL,
      value: description,
    });
    return embedding;
  } catch (error) {
    console.error('[Image Util] Failed to generate embedding:', error);
    return null;
  }
}

/**
 * Inserts image metadata into the database.
 * @param data Object containing image metadata.
 * @returns True if insertion was successful, false otherwise.
 */
async function insertImageRecord(data: {
  blob_url: string;
  description: string;
  embedding: number[];
  hash: string;
  filename: string;
  shortName: string | null;
  blob_pathname: string;
}): Promise<boolean> {
  if (!pool) {
    console.error('[DB Util] Database pool is not available. Cannot insert.');
    return false;
  }
  const client = await pool.connect();
  try {
    const insertQuery = `
      INSERT INTO images (
        blob_url, description, embedding, hash, filename, shortName,
        blob_pathname, layout_hint, image_type, source, created_at
      ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW()
      );
    `;
    await client.query(insertQuery, [
      data.blob_url,
      data.description,
      `[${data.embedding.join(',')}]`, // Format embedding array for pgvector
      data.hash,
      data.filename,
      data.shortName, // Can be null
      data.blob_pathname,
      null, // layout_hint is null for product images
      'product', // image_type
      'getimg.ai', // source
    ]);
    console.log(`[DB Util] Inserted record for ${data.blob_pathname}`);
    return true;
  } catch (error) {
    console.error(
      `[DB Util] Failed to insert record for ${data.blob_pathname}:`,
      error,
    );
    return false;
  } finally {
    client.release();
  }
}

// --- Orchestration Function ---

// Interface for placeholder data expected by the orchestrator
interface ImagePlaceholder {
  originalUrl: string;
  description: string;
}

// Interface for the result returned by the orchestrator
interface ProcessedImageResult {
  originalUrl: string;
  blobUrl: string | null; // Remains the primary return value for the route
}

/**
 * Processes a single image placeholder: generates via getimg.ai, uploads,
 * calculates hash, generates embedding & shortName, inserts into DB.
 * @param placeholder The image placeholder object.
 * @returns A promise resolving to the ProcessedImageResult.
 */
async function processSinglePlaceholder(
  placeholder: ImagePlaceholder,
): Promise<ProcessedImageResult> {
  let getimgUrl: string | null = null;
  let downloadResult: {
    buffer: Buffer;
    filename: string;
    contentType: string | null;
  } | null = null;
  let blobResult: { url: string; pathname: string } | null = null;
  let imageHash: string | null = null;
  let embedding: number[] | null = null;
  let shortName: string | null = null;
  let dbSuccess = false;

  try {
    // 1. Log Original Description & Construct Modified Prompt
    console.log(
      '[getimg.ai Prompt] Original description:',
      placeholder.description,
    );
    // TODO: Add DB column & logic to persist the modifiedPrompt below (see PRD Task 8.4.2.x)
    const modifiedPrompt = `Product photo:
${placeholder.description}

Style: suitable for ecommerce site, clean, white background, centered product shot, no text.`;
    console.log('[getimg.ai Prompt] Modified prompt:', modifiedPrompt);

    // 2. Call getimg.ai with the MODIFIED prompt
    getimgUrl = await callGetImgApi(modifiedPrompt);
    if (!getimgUrl) {
      console.warn(
        `[Image Gen Util] Failed getimg.ai call for: ${placeholder.originalUrl}.`,
      );
      throw new Error('getimg.ai call failed');
    }

    // 3. Download Image
    downloadResult = await downloadImageFromUrl(getimgUrl);
    if (!downloadResult) {
      throw new Error('Image download failed');
    }
    const { buffer: imageBuffer, filename, contentType } = downloadResult;
    const blobPathname = `generated/${filename}`; // Define Blob pathname

    // 4. Upload to Vercel Blob
    console.log(`[Image Gen Util] Uploading image to: ${blobPathname}...`);
    blobResult = await put(blobPathname, imageBuffer, {
      access: 'public',
      contentType: contentType || undefined,
      // No addRandomSuffix needed if getimg filenames are unique enough
    });
    console.log(
      `[Image Gen Util] Upload successful. Blob URL: ${blobResult.url}`,
    );

    // 5. Calculate Hash
    imageHash = calculateHash(imageBuffer);

    // 6. Generate Embedding
    embedding = await generateImageEmbedding(placeholder.description);
    if (!embedding) {
      throw new Error('Embedding generation failed');
    }

    // 7. Generate Short Name
    shortName = await generateShortName(placeholder.description);
    // We proceed even if shortName is null, as it's nullable in DB

    // 8. Insert into Database
    dbSuccess = await insertImageRecord({
      blob_url: blobResult.url,
      description: placeholder.description,
      embedding: embedding,
      hash: imageHash,
      filename: filename,
      shortName: shortName,
      blob_pathname: blobResult.pathname, // Use pathname from blob result
    });
    if (!dbSuccess) {
      throw new Error('Database insertion failed');
    }

    // If all steps succeeded
    return { originalUrl: placeholder.originalUrl, blobUrl: blobResult.url };
  } catch (error) {
    // Log the specific error that caused the failure
    console.error(
      `[Image Gen Util] Failed processing placeholder ${placeholder.originalUrl}:`,
      error instanceof Error ? error.message : error,
    );
    // TODO: Consider cleanup? e.g., delete blob if DB insert failed? For now, leave it.
    return { originalUrl: placeholder.originalUrl, blobUrl: null };
  }
}

/**
 * Processes a list of image placeholders: generates images via getimg.ai,
 * uploads them to Vercel Blob, generates metadata, stores in DB, and returns results.
 * @param placeholders Array of image placeholder objects.
 * @returns A promise resolving to an array of processed image results.
 */
export async function generateAndUploadPlaceholders(
  placeholders: ImagePlaceholder[],
): Promise<Array<ProcessedImageResult>> {
  if (!placeholders || placeholders.length === 0) {
    return [];
  }

  console.log(
    `[Image Gen Util] Starting generation, upload & persistence for ${placeholders.length} images...`,
  );

  // TODO: Implement concurrency limiting (e.g., p-limit)
  const processingPromises = placeholders.map(processSinglePlaceholder);

  // Wait for all operations to settle
  const results = await Promise.allSettled(processingPromises);

  // Process settled results
  const finalResults: Array<ProcessedImageResult> = [];
  let successfulOps = 0;
  let failedOps = 0;

  results.forEach((result, index) => {
    if (result.status === 'fulfilled' && result.value.blobUrl) {
      finalResults.push(result.value);
      successfulOps++;
    } else {
      // Either rejected promise or fulfilled with blobUrl: null
      const originalUrl = placeholders[index]?.originalUrl || 'unknown';
      finalResults.push({ originalUrl: originalUrl, blobUrl: null });
      failedOps++;
      if (result.status === 'rejected') {
        console.error(
          `[Image Gen Util] Unexpected rejection for placeholder ${originalUrl}:`,
          result.reason,
        );
      }
    }
  });

  console.log(
    `[Image Gen Util] Processing finished. Success: ${successfulOps}, Failed: ${failedOps}`,
  );
  return finalResults;
}
