import { put } from '@vercel/blob';
import path from 'node:path';
import { embed, generateText } from 'ai'; // Added for embedding and text gen
import { heliconeOpenAI } from './ai-providers'; // Import new provider
import { pool } from '@/lib/db'; // Added for database access
import { callGetImgApi } from './getimg-api';
import { callFalAiTextToImage } from './fal-api';
import { callOpenAiTextToImage } from './openai-image-api';
import { calculateHash } from './utils';

// --- Types and Constants ---
// Define and EXPORT the generation modes type
export type GenerationMode =
  | 'stock' // Not used in this file directly for generation, but part of the type
  | 'getimg.ai'
  | 'fal.ai-flux-1.1-pro'
  | 'openai-gpt-image-1';

// --- Model Definitions ---
// TODO: Regarding Helicone headers for EMBEDDING_MODEL related `embed` calls:
// Similar to app/lib/image.ts, `embed` calls using this model can accept per-call headers
// via `embed({ model, value }, { headers: perCallHeaders })` if dynamic context is available.
// For now, it relies on static headers from `heliconeOpenAI()` in `ai-providers.ts`.
const EMBEDDING_MODEL = heliconeOpenAI().embedding('text-embedding-3-small');

// TODO: Regarding Helicone headers for SHORT_NAME_MODEL related `generateText` calls:
// `generateText` calls can also accept per-call headers via an options object:
// `generateText({ model, prompt }, { headers: perCallHeaders })`.
// Alternatively, dynamic headers could be passed to `heliconeOpenAI(dynamicHeaders)(modelName)`.
// For now, it relies on static headers from `heliconeOpenAI()` in `ai-providers.ts`.
const SHORT_NAME_MODEL = heliconeOpenAI()('gpt-4o-mini');
const SHORT_NAME_PROMPT_TEMPLATE =
  'Generate a very short (3-5 words) title or label for an image based on the following description: "{description}"';

// --- Helper Function Refactored ---

/**
 * Downloads an image from a URL, returns its buffer and determined filename.
 * @param getimgUrl The URL of the image generated by getimg.ai.
 * @returns Object containing the image buffer, filename, and content type if successful, otherwise null.
 */
async function downloadImageFromUrl(getimgUrl: string): Promise<{
  buffer: Buffer;
  filename: string;
  contentType: string | null;
} | null> {
  try {
    console.debug(`[Image Util] Downloading image from: ${getimgUrl}`);
    const fetchResponse = await fetch(getimgUrl);
    if (!fetchResponse.ok) {
      throw new Error(
        `Failed to download image (${fetchResponse.status}): ${fetchResponse.statusText}`,
      );
    }
    const imageArrayBuffer = await fetchResponse.arrayBuffer();
    const imageBuffer = Buffer.from(imageArrayBuffer); // Convert ArrayBuffer to Buffer
    const contentType = fetchResponse.headers.get('content-type');
    console.debug(`[Image Util] Downloaded ${imageBuffer.byteLength} bytes.`);

    // Determine Filename from getimg.ai URL
    const parsedGetimgUrl = new URL(getimgUrl);
    const getimgFilename = path.basename(parsedGetimgUrl.pathname);
    if (!getimgFilename || getimgFilename === '/' || getimgFilename === '.') {
      throw new Error(
        `Could not extract valid filename from URL: ${getimgUrl}`,
      );
    }
    return { buffer: imageBuffer, filename: getimgFilename, contentType };
  } catch (error) {
    console.error(`[Image Util] Error downloading ${getimgUrl}:`, error);
    return null;
  }
}

/**
 * Generates a short name for an image based on its description.
 * @param description The image description.
 * @returns The generated short name, or null on failure.
 */
async function generateShortName(description: string): Promise<string | null> {
  if (!description) return null;
  try {
    const prompt = SHORT_NAME_PROMPT_TEMPLATE.replace(
      '{description}',
      description,
    );
    // TODO: If dynamic per-call Helicone headers become available for short name generation,
    // pass them as a second argument to `generateText`: e.g., { headers: dynamicHeaders }.
    // Relies on provider-level Helicone headers for now.
    const { text } = await generateText({
      model: SHORT_NAME_MODEL,
      prompt: prompt,
      system:
        'You are a helpful AI that generates short names for images. You output just the name, no other text.',
      maxTokens: 20, // Limit tokens for a short name
    });
    return text.trim();
  } catch (error) {
    console.error('[Image Util] Failed to generate short name:', error);
    return null;
  }
}

/**
 * Generates an embedding for a given text description.
 * @param description The text description.
 * @returns The embedding vector, or null on failure.
 */
async function generateImageEmbedding(
  description: string,
): Promise<number[] | null> {
  if (!description) return null;
  try {
    // TODO: If dynamic per-call Helicone headers become available for embeddings generated here,
    // pass them as a second argument to `embed`: e.g., { headers: dynamicHeaders }.
    // Relies on provider-level Helicone headers for now.
    const { embedding } = await embed({
      model: EMBEDDING_MODEL,
      value: description,
    });
    return embedding;
  } catch (error) {
    console.error('[Image Util] Failed to generate embedding:', error);
    return null;
  }
}

/**
 * Inserts image metadata into the database.
 * @param data Object containing image metadata, including the generation source.
 * @returns True if insertion was successful, false otherwise.
 */
async function insertImageRecord(data: {
  blob_url: string;
  description: string;
  embedding: number[];
  hash: string;
  filename: string;
  shortName: string | null;
  blob_pathname: string;
  source: string; // Source API ('getimg.ai', 'fal.ai-flux-1.1-pro', etc.)
  generationPrompt?: string;
  imageType: 'product' | 'hero'; // Added: Type of image
  layoutHint?: 'left' | 'right' | 'center' | null; // Added: Layout hint for heroes
}): Promise<boolean> {
  if (!pool) {
    console.error('[DB Util] Database pool is not available. Cannot insert.');
    return false;
  }
  const client = await pool.connect();
  try {
    const insertQuery = `
      INSERT INTO images (
        blob_url, description, embedding, hash, filename, shortName,
        blob_pathname, layout_hint, image_type, source, created_at,
        generation_prompt
      ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(),
        $11
      );
    `;
    await client.query(insertQuery, [
      data.blob_url,
      data.description,
      `[${data.embedding.join(',')}]`, // Format embedding array for pgvector
      data.hash,
      data.filename,
      data.shortName, // Can be null
      data.blob_pathname,
      data.layoutHint ?? null, // Use provided hint or null
      data.imageType, // Use provided type
      data.source,
      data.generationPrompt,
    ]);
    console.log(
      `[DB Util] Inserted record for ${data.blob_pathname} (Source: ${data.source})`,
    );
    return true;
  } catch (error) {
    console.error(
      `[DB Util] Failed to insert record for ${data.blob_pathname} (Source: ${data.source}):`,
      error,
    );
    return false;
  } finally {
    client.release();
  }
}

// --- Orchestration Function ---

// Interface for placeholder data expected by the orchestrator
interface ImagePlaceholder {
  originalUrl: string;
  description: string;
}

// Interface for the result of processing a single placeholder
interface ProcessedImageResult {
  originalUrl: string;
  blobUrl: string | null; // null if processing failed
}

/**
 * Processes a single image placeholder: generates via the specified API,
 * uploads, calculates hash, generates embedding & shortName, inserts into DB.
 * @param placeholder The image placeholder object.
 * @param generationMode The selected image generation mode/API.
 * @param imageType The type of the image.
 * @param alignment The alignment of the image.
 * @param imageStyle The image style (general style for product images consistent with the store concept).
 * @returns A promise resolving to the ProcessedImageResult.
 */
export async function processSinglePlaceholder(
  placeholder: ImagePlaceholder,
  generationMode: GenerationMode,
  imageType: 'product' | 'hero',
  alignment?: 'left' | 'right' | 'center' | null,
  imageStyle?: string | null,
): Promise<ProcessedImageResult> {
  // Variables to hold intermediate results
  let externalImageUrl: string | null = null; // URL from GetImg/Fal
  let blobUrlFromOpenAI: string | null = null; // Direct Blob URL from OpenAI helper
  let openAiResult: { blobUrl: string; hash: string } | null = null;
  const sourceApi = generationMode; // Source string matches mode name (Use const - Linter fix)

  let downloadResult: {
    buffer: Buffer;
    filename: string;
    contentType: string | null;
  } | null = null;
  let blobResult: { url: string; pathname: string } | null = null;
  let imageHash: string | null = null;
  let embedding: number[] | null = null;
  let shortName: string | null = null;
  let dbSuccess = false;

  try {
    // 1. Log Original Description & Construct Modified Prompt
    console.log(
      `Starting processing for description: ${placeholder.description.substring(0, 50)}...`,
    );

    let modifiedPrompt = '';

    if (imageType === 'hero') {
      // Construct prompt for Hero images, incorporating alignment
      let alignmentInstruction = '';
      if (alignment === 'left') {
        alignmentInstruction =
          'The image is aligned to the right, leaving the left side blank or with a neutral background suitable for text overlay.';
      } else if (alignment === 'right') {
        alignmentInstruction =
          'The image is aligned to the left, leaving the right side blank or with a neutral background suitable for text overlay.';
      } else if (alignment === 'center') {
        // TODO: Define center alignment instruction if needed
        alignmentInstruction =
          'The main subject is centered, potentially with balanced neutral space on both sides.'; // Placeholder
      }
      modifiedPrompt = `${placeholder.description}. ${alignmentInstruction}`;
      // Note: imageStyle is currently ignored for heroes, based on user feedback.
      console.debug(
        `[Image Gen Util - ${generationMode}] Using Style: Alignment-based Prompt (Hero)`,
      );
    } else if (imageType === 'product') {
      // Construct prompt for Product images (existing logic)
      const defaultStyle = `Displayed in perfect profile against a plain light-grey studio background, centred, soft diffused lighting.\n\nClean, calm, modern — ideal for premium e-commerce display.`;
      const finalStyle = imageStyle?.trim() ? imageStyle : defaultStyle;
      modifiedPrompt = `${placeholder.description}\n\n${finalStyle}`;
      console.debug(
        `[Image Gen Util - ${generationMode}] Using Style:`,
        imageStyle?.trim()
          ? `"${imageStyle}" (From Settings)`
          : 'Default Template',
      );
    } else {
      // Should not happen with current types, but good practice to handle
      console.error(`[Image Gen Util] Unknown imageType: ${imageType}`);
      throw new Error(`Unsupported imageType: ${imageType}`);
    }

    console.debug(
      `[Image Gen Util - ${generationMode}] Final generation prompt:`,
      modifiedPrompt,
    );

    // 2. Call the selected Generation API
    console.log(`Calling ${generationMode} API...`);
    switch (generationMode) {
      case 'getimg.ai':
        externalImageUrl = await callGetImgApi(modifiedPrompt);
        break;
      case 'fal.ai-flux-1.1-pro':
        externalImageUrl = await callFalAiTextToImage(modifiedPrompt);
        break;
      case 'openai-gpt-image-1':
        openAiResult = await callOpenAiTextToImage(modifiedPrompt);
        blobUrlFromOpenAI = openAiResult?.blobUrl ?? null;
        imageHash = openAiResult?.hash ?? null;
        break;
      default:
        console.error(
          `[Image Gen Util] Unknown generation mode: ${generationMode}`,
        );
        throw new Error(`Unknown generation mode: ${generationMode}`);
    }
    console.log(`API call completed`);

    // Check if API call failed
    if (!externalImageUrl && !blobUrlFromOpenAI) {
      console.warn(
        `[Image Gen Util - ${generationMode}] API call failed for: ${placeholder.originalUrl}.`,
      );
      throw new Error(`${generationMode} API call failed`);
    }

    // --- Process the result (Download/Upload if necessary) ---
    let finalBlobUrl: string | null = null;
    let finalBlobPathname: string | null = null;
    let finalFilename: string | null = null;
    let finalImageBuffer: Buffer | null = null;

    if (blobUrlFromOpenAI && openAiResult) {
      // Check openAiResult for safety
      // OpenAI already uploaded, use its details
      finalBlobUrl = openAiResult.blobUrl;
      imageHash = openAiResult.hash; // Use hash from result
      // Derive pathname and filename from URL (best effort)
      try {
        const url = new URL(finalBlobUrl);
        finalBlobPathname = url.pathname.substring(1); // Remove leading '/'
        finalFilename = path.basename(finalBlobPathname);
      } catch {
        /* ignore parsing errors */
      }
    } else if (externalImageUrl) {
      // GetImg/Fal returned an external URL, need to download and upload
      // 3. Download Image
      console.debug(
        `[Image Gen Util - ${generationMode}] Downloading from external URL...`,
      );
      downloadResult = await downloadImageFromUrl(externalImageUrl);
      if (!downloadResult) {
        throw new Error('Image download failed');
      }
      const { buffer: imageBuffer, filename, contentType } = downloadResult;
      finalFilename = filename;
      finalImageBuffer = imageBuffer;
      const blobPathname = `generated/${filename}`; // Define Blob pathname

      // 4. Upload to Vercel Blob
      console.debug(
        `[Image Gen Util - ${generationMode}] Uploading image to: ${blobPathname}...`,
      );
      blobResult = await put(blobPathname, imageBuffer, {
        access: 'public',
        contentType: contentType || undefined,
      });
      console.debug(
        `[Image Gen Util - ${generationMode}] Upload successful. Blob URL: ${blobResult.url}`,
      );
      finalBlobUrl = blobResult.url;
      finalBlobPathname = blobResult.pathname;
      // Calculate hash if buffer exists (only for non-OpenAI flow now)
      if (finalImageBuffer) {
        imageHash = calculateHash(finalImageBuffer);
      }
    }

    // Ensure we have a final Blob URL, pathname, filename and hash
    if (!finalBlobUrl || !finalBlobPathname || !finalFilename || !imageHash) {
      console.error('[Image Gen Util] Missing required data after processing', {
        finalBlobUrl,
        finalBlobPathname,
        finalFilename,
        imageHash,
      });
      throw new Error(
        'Failed to obtain final Blob URL, pathname, filename, or hash.',
      );
    }

    // 6. Generate Embedding
    embedding = await generateImageEmbedding(placeholder.description);
    if (!embedding) {
      throw new Error('Embedding generation failed');
    }

    // 7. Generate Short Name
    shortName = await generateShortName(placeholder.description);
    // We proceed even if shortName is null, as it's nullable in DB

    // 8. Insert into Database (using the determined source and final details)
    dbSuccess = await insertImageRecord({
      blob_url: finalBlobUrl,
      description: placeholder.description,
      embedding: embedding,
      hash: imageHash,
      filename: finalFilename,
      shortName: shortName,
      blob_pathname: finalBlobPathname,
      source: sourceApi, // Pass the determined source API
      generationPrompt: modifiedPrompt,
      imageType: imageType, // Pass the determined image type
      layoutHint: imageType === 'hero' ? alignment : null, // Pass alignment as hint only for heroes
    });
    if (!dbSuccess) {
      throw new Error('Database insertion failed');
    }

    // If all steps succeeded
    console.log(`Successfully completed all processing steps`);
    return { originalUrl: placeholder.originalUrl, blobUrl: finalBlobUrl };
  } catch (error) {
    console.error(
      `Failed processing: ${error instanceof Error ? error.message : error}`,
    );
    return { originalUrl: placeholder.originalUrl, blobUrl: null };
  }
}
