import { put } from '@vercel/blob';
import path from 'node:path';
import { callGetImgApi } from './getimg-api'; // Assuming getimg-api.ts is in the same lib folder

// --- Helper Function for Single Image Upload ---

/**
 * Downloads an image from a URL, uploads it to Vercel Blob under 'generated/',
 * using the filename from the original URL.
 * @param getimgUrl The URL of the image generated by getimg.ai
 * @returns The Vercel Blob URL if successful, otherwise null.
 */
async function uploadGeneratedImageToBlob(
  getimgUrl: string,
): Promise<string | null> {
  try {
    // Download image
    console.log(`[Blob Util] Downloading image from: ${getimgUrl}`);
    const fetchResponse = await fetch(getimgUrl);
    if (!fetchResponse.ok) {
      throw new Error(
        `Failed to download image (${fetchResponse.status}): ${fetchResponse.statusText}`,
      );
    }
    const imageBuffer = await fetchResponse.arrayBuffer();
    console.log(`[Blob Util] Downloaded ${imageBuffer.byteLength} bytes.`);

    // Determine Blob Pathname from getimg.ai URL
    const parsedGetimgUrl = new URL(getimgUrl);
    const getimgFilename = path.basename(parsedGetimgUrl.pathname);
    if (!getimgFilename || getimgFilename === '/' || getimgFilename === '.') {
      // Added '.' check for safety
      throw new Error(
        `Could not extract valid filename from URL: ${getimgUrl}`,
      );
    }
    const blobPathname = `generated/${getimgFilename}`;
    console.log(`[Blob Util] Determined pathname: ${blobPathname}`);

    // Upload to Vercel Blob
    console.log(`[Blob Util] Uploading image to: ${blobPathname}...`);
    const blob = await put(blobPathname, imageBuffer, {
      access: 'public',
      // Add content type header if available from fetch response
      contentType: fetchResponse.headers.get('content-type') || undefined,
    });
    console.log(`[Blob Util] Upload successful. Blob URL: ${blob.url}`);

    return blob.url;
  } catch (error) {
    console.error(
      `[Blob Util] Error processing image URL ${getimgUrl}:`,
      error,
    );
    return null; // Return null on download/upload error
  }
}

// --- Orchestration Function ---

// Interface for placeholder data expected by the orchestrator
interface ImagePlaceholder {
  originalUrl: string;
  description: string;
}

// Interface for the result returned by the orchestrator
interface ProcessedImageResult {
  originalUrl: string;
  blobUrl: string | null;
}

/**
 * Processes a list of image placeholders: generates images via getimg.ai,
 * uploads them to Vercel Blob, and returns the results.
 * @param placeholders Array of image placeholder objects.
 * @returns A promise resolving to an array of processed image results.
 */
export async function generateAndUploadPlaceholders(
  placeholders: ImagePlaceholder[],
): Promise<Array<ProcessedImageResult>> {
  if (!placeholders || placeholders.length === 0) {
    return [];
  }

  console.log(
    `[Image Gen Util] Starting generation & upload for ${placeholders.length} images...`,
  );

  // TODO: Implement concurrency limiting (e.g., p-limit) if needed for Blob uploads.
  const processingPromises = placeholders.map(
    async (p): Promise<ProcessedImageResult> => {
      const getimgUrl = await callGetImgApi(p.description);

      if (!getimgUrl) {
        console.warn(
          `[Image Gen Util] Failed getimg.ai call for: ${p.originalUrl}. Skipping upload.`,
        );
        return { originalUrl: p.originalUrl, blobUrl: null };
      }

      // If getimg.ai call succeeded, attempt upload
      const blobUrl = await uploadGeneratedImageToBlob(getimgUrl);
      // uploadGeneratedImageToBlob handles its own errors and returns null on failure

      return { originalUrl: p.originalUrl, blobUrl: blobUrl };
    },
  );

  // Wait for all operations to settle
  const results = await Promise.allSettled(processingPromises);

  // Process settled results
  const finalResults: Array<ProcessedImageResult> = [];
  let successfulUploads = 0;
  let failedOps = 0; // Includes getimg failures + upload failures

  results.forEach((result, index) => {
    if (result.status === 'fulfilled') {
      finalResults.push(result.value);
      if (result.value.blobUrl) {
        successfulUploads++;
      } else {
        failedOps++;
      }
    } else {
      // Should not happen often due to structure, but log if it does
      console.error(
        `[Image Gen Util] Unexpected failure for placeholder ${placeholders[index]?.originalUrl}:`,
        result.reason,
      );
      finalResults.push({
        originalUrl: placeholders[index]?.originalUrl || 'unknown',
        blobUrl: null,
      });
      failedOps++;
    }
  });

  console.log(
    `[Image Gen Util] Processing finished. Success: ${successfulUploads}, Failed/Skipped: ${failedOps}`,
  );
  return finalResults;
}
