/**
 * @file app/lib/theme.ts
 * @description This module is responsible for managing theme-related configurations and logic
 * for the AI-generated store content. It defines default color palettes and section themes,
 * and provides a function to inject these defaults into the JSON structure generated by the AI.
 * This helps in maintaining a consistent visual appearance for stores and simplifies the
 * AI's task by offloading theme generation to the backend.
 */

import type { ColorPalette } from '../../constants/palettes';
import { AVAILABLE_PALETTES, DEFAULT_PALETTE } from '../../constants/palettes';

/**
 * Applies a chosen or default theme (global and section-specific colors) to the AI-generated JSON.
 * @param json The AI-generated JSON data.
 * @param chosenPaletteName The name of the palette chosen by the AI, or null/undefined to use default.
 * @returns The JSON data with the theme injected.
 */
export function applyTheme(json: any, chosenPaletteName?: string | null): any {
  if (!json || typeof json !== 'object') {
    console.warn('applyTheme: Invalid JSON input, returning as is.');
    return json;
  }

  let paletteToApply: ColorPalette = DEFAULT_PALETTE;
  if (chosenPaletteName && AVAILABLE_PALETTES[chosenPaletteName]) {
    paletteToApply = AVAILABLE_PALETTES[chosenPaletteName];
    console.log(`applyTheme: Applying chosen palette: ${chosenPaletteName}`);
  } else {
    console.log(
      `applyTheme: Applying default palette: ${DEFAULT_PALETTE.name}`,
    );
    if (chosenPaletteName) {
      console.warn(
        `applyTheme: Chosen palette name "${chosenPaletteName}" not found. Falling back to default.`,
      );
    }
  }

  // Ensure settings and settings.colors objects exist
  if (!json.settings) {
    json.settings = {};
  }
  if (!json.settings.colors) {
    json.settings.colors = {};
  }

  // Inject global colors from the selected palette
  if (json.settings.colors.palette) {
    console.warn(
      'applyTheme: AI unexpectedly generated settings.colors.palette. Overwriting with selected palette.',
    );
  }
  json.settings.colors.palette = paletteToApply.globalPalette;
  json.settings.colors.paletteName = paletteToApply.name;

  // Inject section themes from the selected palette
  if (json.paths && typeof json.paths === 'object') {
    for (const pathKey in json.paths) {
      if (Array.isArray(json.paths[pathKey])) {
        for (const section of json.paths[pathKey]) {
          if (section?.id && typeof section.id === 'string') {
            if (section.theme) {
              console.warn(
                `applyTheme: AI unexpectedly generated theme for section ${section.id}. Overwriting with selected palette.`,
              );
            }

            const sectionThemeFromPalette =
              paletteToApply.sectionThemes[
                section.id as keyof typeof paletteToApply.sectionThemes
              ];

            if (sectionThemeFromPalette) {
              section.theme = sectionThemeFromPalette;
            } else {
              // If a section type is not in our selected palette's sectionThemes map,
              // assign an empty theme object. This handles sections that don't have
              // specific theme overrides in the palette or are new/unrecognized.
              console.warn(
                `applyTheme: Section ${section.id} has no specific theme in palette "${paletteToApply.name}". Setting theme: {}.`,
              );
              section.theme = {};
            }
          } else {
            console.warn(
              'applyTheme: Encountered a section without a valid string `id` property:',
              section,
            );
          }
        }
      }
    }
  }
  return json;
}
