/**
 * @file app/lib/theme.ts
 * @description This module is responsible for managing theme-related configurations and logic
 * for the AI-generated store content. It defines default color palettes and section themes,
 * and provides a function to inject these defaults into the JSON structure generated by the AI.
 * This helps in maintaining a consistent visual appearance for stores and simplifies the
 * AI's task by offloading theme generation to the backend.
 */

// --- Default Theme Definitions ---
export const DEFAULT_GLOBAL_PALETTE_OKLCH = {
  theme: { background: '100% 0 0' }, // Example from original prompt
  'theme-primary': { DEFAULT: '50% 0.15 210', background: '95% 0.05 210' }, // Example from original prompt
  'theme-button': { DEFAULT: '50% 0.15 210', background: '85% 0.1 210' }, // Example from original prompt
  // Example from original prompt (theme-nav was present in one example)
  'theme-nav': { DEFAULT: '13.63% 0.0364 259.2', background: '100% 0 0' },
};

export const DEFAULT_SECTION_THEMES_HEX = {
  HeroSection: {
    color: '#111827', // Example from original prompt
    buttonBackgroundColor: '#059669', // Example from original prompt
    buttonTextColor: '#ffffff', // Example from original prompt
    buttonHoverBackgroundColor: '#047857', // Example from original prompt
  },
  Nav: {
    backgroundColor: '#ffffff', // Example from original prompt
    hoverBackgroundColor: '#e5e7eb', // Made up, but plausible hover for white
    color: '#007bff', // Example from original prompt
  },
  Footer: {
    backgroundColor: '#333333', // Example from original prompt
    color: '#ffffff', // Example from original prompt
  },
  ProductDetails: {
    color: '#1f2937', // Made up, but plausible text color
    buttonBackgroundColor: '#059669', // Matching Hero button
    buttonHoverBackgroundColor: '#047857', // Matching Hero button
    buttonTextColor: '#ffffff', // Matching Hero button
  },
  BannerSection: {
    backgroundColor: '#f3f4f6', // Made up, light gray
    textColor: '#1f2937', // Made up, dark gray
  },
  // Sections that should have an empty theme object to inherit global styles
  ProductGrid: {},
  CollectionGrid: {},
  Children: {},
  Title: {},
  Markdown: {},
  ProductDescription: {},
  RelatedProducts: {},
  ReviewList: {},
  FeatureSection: {},
  CategoryMenu: {
    // Although out of scope in prompt, if it appears, give it a theme like Nav
    backgroundColor: '#ffffff',
    hoverBackgroundColor: '#e5e7eb',
    color: '#007bff',
  },
  Breadcrumbs: {},
  QuestionList: {},
};
// --- End Default Theme Definitions ---

/**
 * Injects a default theme (global and section-specific colors) into the AI-generated JSON.
 * @param json The AI-generated JSON data.
 * @returns The JSON data with the default theme injected.
 */
export function injectDefaultTheme(json: any): any {
  if (!json || typeof json !== 'object') {
    console.warn('injectDefaultTheme: Invalid JSON input, returning as is.');
    return json;
  }

  // Inject global colors
  if (!json.settings) {
    json.settings = {};
  }
  if (json.settings.colors) {
    console.warn(
      'injectDefaultTheme: AI unexpectedly generated settings.colors. Overwriting with default.',
    );
  }
  json.settings.colors = {
    palette: DEFAULT_GLOBAL_PALETTE_OKLCH,
    paletteName: 'default', // Set a default palette name
  };

  // Inject section themes
  if (json.paths && typeof json.paths === 'object') {
    for (const pathKey in json.paths) {
      if (Array.isArray(json.paths[pathKey])) {
        for (const section of json.paths[pathKey]) {
          // Use section.id (expecting AI to output 'id' now based on updated prompt)
          if (section?.id && typeof section.id === 'string') {
            if (section.theme) {
              console.warn(
                // Use section.id in log message
                `injectDefaultTheme: AI unexpectedly generated theme for section ${section.id}. Overwriting with default.`,
              );
            }
            if (
              Object.prototype.hasOwnProperty.call(
                DEFAULT_SECTION_THEMES_HEX,
                section.id, // Use section.id for lookup
              )
            ) {
              section.theme =
                DEFAULT_SECTION_THEMES_HEX[
                  section.id as keyof typeof DEFAULT_SECTION_THEMES_HEX // Use section.id for access
                ];
            } else {
              // If a section type is not in our default map, it should likely still have a theme object,
              // possibly empty, if the YNS API expects it.
              // For now, let's assume an empty theme object is safer than 'undefined' or deleting the key
              // if the section type is unrecognized but a theme property might be expected.
              console.warn(
                // Use section.id in log message
                `injectDefaultTheme: Section ${section.id} has no specific default theme in map. Setting theme: {}.`,
              );
              section.theme = {}; // Assign an empty object for unmapped sections
            }
          } else {
            // Log if a section doesn't have an 'id' or if it's not a string
            console.warn(
              'injectDefaultTheme: Encountered a section without a valid string `id` property:',
              section,
            );
          }
        }
      }
    }
  }
  return json;
}
